services:
  app:
    image: best_insurance/api:latest
    platform: linux/arm64

    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/best_insurance
      SPRING_DATASOURCE_USERNAME: bestinsurance
      SPRING_DATASOURCE_PASSWORD: bestinsurance
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      BPL_DEBUG_ENABLED: "true"
      BPL_DEBUG_PORT: 5005
      BPL_DEBUG_SUSPEND: "false"
    ports:
      - "8080:8080"
      - "5005:5005"
  db:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_DB: best_insurance
      POSTGRES_USER: bestinsurance
      POSTGRES_PASSWORD: bestinsurance
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8081:8080"
